// ✅ Auto-generated by generate_tool_map.py
import dynamic from "next/dynamic";

const MarkdownToHtml = dynamic(() => import("@/app/components/tools/Development/MarkdownToHtml/MarkdownToHtml"), { ssr: false });
import ImageCompressor from "@/app/components/tools/ImageGraphics/ImageCompressor/ImageCompressor";
import CubicSolver from "@/app/components/tools/MathConversion/CubicSolver/CubicSolver";
import QuadraticSolver from "@/app/components/tools/MathConversion/QuadraticSolver/QuadraticSolver";
import FileZipConverter from "@/app/components/tools/Productivity/FileZipConverter/FileZipConverter";
const PdfTextExtractor = dynamic(() => import("@/app/components/tools/Productivity/PdfTextExtractor/PdfTextExtractor"), { ssr: false });
import UnzipTool from "@/app/components/tools/Productivity/UnzipTool/UnzipTool";
import KeywordDensityAnalyzer from "@/app/components/tools/SeoWeb/KeywordDensityAnalyzer/KeywordDensityAnalyzer";
import MetatagChecker from "@/app/components/tools/SeoWeb/MetatagChecker/MetatagChecker";
import SeoVerifier from "@/app/components/tools/SeoWeb/SeoVerifier/SeoVerifier";
import SitemapValidator from "@/app/components/tools/SeoWeb/SitemapValidator/SitemapValidator";
import FontPair from "@/app/components/tools/TextWriting/FontPair/FontPair";
import InstagramBioGenerator from "@/app/components/tools/TextWriting/InstagramBioGenerator/InstagramBioGenerator";
import WordCounter from "@/app/components/tools/TextWriting/WordCounter/WordCounter";

const toolComponentMap: Record<string, React.ComponentType> = {
  "MarkdownToHtml": MarkdownToHtml,
  "ImageCompressor": ImageCompressor,
  "CubicSolver": CubicSolver,
  "QuadraticSolver": QuadraticSolver,
  "FileZipConverter": FileZipConverter,
  "PdfTextExtractor": PdfTextExtractor,
  "UnzipTool": UnzipTool,
  "KeywordDensityAnalyzer": KeywordDensityAnalyzer,
  "MetatagChecker": MetatagChecker,
  "SeoVerifier": SeoVerifier,
  "SitemapValidator": SitemapValidator,
  "FontPair": FontPair,
  "InstagramBioGenerator": InstagramBioGenerator,
  "WordCounter": WordCounter,
};

export default toolComponentMap;
